# Generated by Django 4.0.6 on 2022-08-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_path', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production_countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(blank=True, max_length=4)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spoken_languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(blank=True, max_length=4)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('adult', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=250, null=True)),
                ('homepage', models.CharField(blank=True, max_length=250)),
                ('imdb_id', models.CharField(blank=True, max_length=250)),
                ('original_language', models.CharField(blank=True, max_length=4)),
                ('original_title', models.CharField(blank=True, max_length=250)),
                ('overview', models.TextField(blank=True, max_length=200, null=True)),
                ('popularity', models.FloatField(default=None, null=True)),
                ('poster_path', models.CharField(default=None, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.CharField(default=None, max_length=250, null=True)),
                ('runtime', models.CharField(default=None, max_length=250, null=True)),
                ('status', models.CharField(default=None, max_length=50, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('title', models.CharField(default=None, max_length=250, null=True)),
                ('video', models.BooleanField(default=False, null=True)),
                ('vote_average', models.FloatField(default=None, null=True)),
                ('vote_count', models.IntegerField()),
                ('genres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.genres')),
                ('production_companies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.production_companies')),
                ('spoken_languages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.spoken_languages')),
            ],
        ),
    ]
