# Generated by Django 4.0.6 on 2022-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='production_companies',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='production_countries',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='spoken_languages',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
