# Generated by Django 4.0.6 on 2022-08-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_genres_movie_production_companies_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Production_companies',
        ),
        migrations.DeleteModel(
            name='Production_countries',
        ),
        migrations.DeleteModel(
            name='Spoken_languages',
        ),
    ]
